// BOOLEAN
var five = 5;
var ten = 10;
console.log("Test 1: Five is equal to 5?");
console.log(five == 5);
console.log("\nTest 2: Ten is equal to 10?");
console.log(ten == 10);
console.log("\nTest 3: Five is not equal to 10?");
console.log(five != 10);
console.log("\nTest 4: Ten is greater than 5?");
console.log(ten > 5);
console.log("\nTest 5: five is less than 10?");
console.log(five < 10);
console.log("\nTest 6: Ten is smaller than 5?");
console.log(ten < 5);
console.log("\nTest 7: Five is equal to ten?");
console.log(five == 10);
console.log("\nTest 8: 10 is not equal to 10?");
console.log(ten != ten);
console.log("\nTest 9: 5 is greater than 10?");
console.log(5 > 10);
console.log("\nTest 10: 50 is smaller 40?");
console.log(50 < 40);
;
